version: '3.9'
services:

  #Builder
  builder:
    container_name: builder
    build:
      context: .
      target: builder
    ports:
      - "4200:4200"
    depends_on:
      - json-server
    networks:
        - MyDevStack
  #Json Server
  json-server:
    container_name: json-server-container
    build:
      context: .
      target: json-server
    ports:
      - "3000:3000"
    volumes:
      - ./db.json:/data/db.json
    networks:
        - MyDevStack

volumes:
    db_data: {}

networks:
    MyDevStack: {}